image: docker:latest

services:
  - docker:dind

build:
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/elkya/docker-npm-bower-gulp-compass .
    - docker push $CI_REGISTRY/elkya/docker-npm-bower-gulp-compass
