image: docker:latest

services:
  - docker:dind

build:
  script:
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD project.elkya.com
    - docker build -t elkya/docker-npm-bower-gulp-compass .
    - docker push elkya/docker-npm-bower-gulp-compass
